### PR TITLE
Add anchors to elements

### PR DESCRIPTION
**Pull request by andrepolo**
Just the rough implementation, you can finish it off or we do it together

### CODE REVIEW

**Comment by sinnbeck** [comment]
Its close. A few things

Change the toHtml method to this
```
public function toHtml($markdown)
    {
        $this->markdown = $markdown;
        $html = $this->converter->convertToHtml($this->markdown);

        $dom = HtmlPageCrawler::create('<div>' . $html . '</div>');

        $this->addCodeHighlights($dom);

        $this->addClasses($dom);

        $this->addAnchorTags($dom);

        return trim($dom->first()->html());
    }
```
And set the add tags default in the config to false :) It should a an option you can turn on if you want it (not forced as default)

After that you should only have your new test that fails, and this is because it assumes that the <a> is around, when it is before :)

If you fix these few things, I will merge

**Comment by andrepolo** [comment]
"And set the add tags default in the config to false..."
Yeah, sure. That's how it should be. 

"After that you should only have your new test that fails..." 
I just cleaned up the code, left the test as it was. Try to get the test running.

**Comment by sinnbeck** [comment]
Thanks for the PR! :)

**Comment by andrepolo** [comment]
You're welcome

**Pull request merged**
